#!/usr/bin/env bash

sudo pacman -S zsh
sudo pacman -S stow
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,home,nvim, git-endeavour, tmux, config, kitty, starship"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi


STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES
